Program LinearEquations
  use magma
  use cudafor
  use iso_c_binding
  Implicit none

  Real (KIND=C_DOUBLE) :: B(3,3), A(3,3), tau(3), work(3)
  Real (KIND=C_DOUBLE), device, dimension(:,:), allocatable :: dB, dA
  Integer (KIND=C_INT) :: i, j, k, l, lwork = 9, ok, status

  status = magma_init()

  A(1,1)=3
  A(1,2)=1
  A(1,3)=5
  A(2,1)=1
  A(2,2)=6
  A(2,3)=5
  A(3,1)=3
  A(3,2)=7
  A(3,3)=8

  print*, "Computing MAGMA"
  status = MAGMA_DGEQRF_GPU(3, 3, A, 3, tau, work, lwork, ok)

  B(1,1)=3
  B(1,2)=1
  B(1,3)=5
  B(2,1)=1
  B(2,2)=6
  B(2,3)=5
  B(3,1)=3
  B(3,2)=7
  B(3,3)=8
  print*, "Compuing LAPACK"
! print the vector x
  call DGEQRF(3,3,B,3,tau,work,lwork,ok)

  do i=1, 3
    do j = 1, 3
      if (real(A(i,j)) /= real(B(i,j))) then
        print*, "TEST FAIL"
        do k=1, 3
          do l = 1, 3
            write(*,*) A(k,l)
          end do
        end do
        do k=1, 3
          do l = 1, 3
            write(*,*) B(k,l)
          end do
        end do
        call exit(1)
      endif
    end do
  end do
  print*, "TEST SUCCESSFUL!"
end
