Program LinearEquations
  use magma_device
  use cudafor
  use iso_c_binding
  Implicit none

  Real (KIND=C_DOUBLE) :: A(3,3), C(3,3)
  Real (KIND=C_DOUBLE),device,dimension(:,:),allocatable :: dA
  Integer (KIND=C_INT) :: i, j, k, l, pivot(3), ok, status

  status = magma_init()

  allocate(dA(3,3))

  A(1,1)=3
  A(1,2)=1
  A(1,3)=5
  A(2,1)=1
  A(2,2)=6
  A(2,3)=5
  A(3,1)=3
  A(3,2)=7
  A(3,3)=8
  dA = A

  print*, "Computing Magma"

  status = MAGMA_DGETRF_GPU(3, 3, dA, 3, pivot, ok)
  A = dA

  C(1,1)=3
  C(1,2)=1
  C(1,3)=5
  C(2,1)=1
  C(2,2)=6
  C(2,3)=5
  C(3,1)=3
  C(3,2)=7
  C(3,3)=8
  print*, "Computing LAPACK"

  call DGETRF(3,3,C,3,pivot,ok)

  do i=1, 3
    do j = 1, 3
      if (real(A(i,j)) /= real(C(i,j))) then
        print*, "TEST FAIL"
        do k=1, 3
          do l = 1, 3
            write(*,*) A(k,l)
          end do
        end do
        do k=1, 3
          do l = 1, 3
            write(*,*) C(k,l)
          end do
        end do
        call exit(1)
      endif
    end do
  end do
  print*, "TEST SUCCESSFUL!"
end
