Program LinearEquations
  use magma_device
  use cudafor
  use iso_c_binding
  Implicit none

  Character (KIND=C_CHAR) :: trans = 'N'
  Real (KIND=C_FLOAT) :: A(3,3), C(3,3), B(3), D(3), temp = 0
  Real (KIND=C_FLOAT),device,dimension(:,:),allocatable :: dA
  Real (KIND=C_FLOAT),device,dimension(:),allocatable :: dB
  Integer (KIND=C_INT) :: i, j, k, l, pivot(3), ok, status
  Integer (KIND=C_INT) :: n = 3, nrhs = 1, lda = 3, ldb = 3

  status = magma_init()

  allocate(dA(3,3))
  allocate(dB(3))

  A(1,1)=3
  A(1,2)=1
  A(1,3)=5
  A(2,1)=1
  A(2,2)=6
  A(2,3)=5
  A(3,1)=3
  A(3,2)=7
  A(3,3)=8

  B(1)=-1.3
  B(2)=-0.1
  B(3)=1.8

  dA = A
  dB = B

  status = magma_init()
  print*, "Running SGETRF on da"
  status = MAGMA_SGETRF_GPU(n, n, dA, n, pivot, ok)
  print*, "Computing Magma"
  status = MAGMA_SGETRS_GPU(trans, n, nrhs, dA, lda, pivot, dB, ldb, ok)
  B = dB

  C(1,1)=3
  C(1,2)=1
  C(1,3)=5
  C(2,1)=1
  C(2,2)=6
  C(2,3)=5
  C(3,1)=3
  C(3,2)=7
  C(3,3)=8
  D(1)=-1.3
  D(2)=-0.1
  D(3)=1.8
  print*, "Computing LAPACK"
  call SGETRF(n,n,C,n,pivot,ok)
  call SGETRS(trans, n,nrhs,C,lda,pivot,D,ldb,ok)

  do i=1, 3
      temp = abs(real(B(i)) - real(D(i)))
      if (temp > .000001) then
        print*, "TEST FAIL"
        do k=1, 3
            write(*,*) B(k)
        end do
        do k=1, 3
            write(*,*) D(k)
        end do
        call exit(1)
      endif
    end do
  print*, "TEST SUCCESSFUL!"
end
